### ISSUE TITLE
Damage not displaying on some targets

### ISSUE THREAD

**Issue by TrippyDedd** [bkader/NameplateSCT_WoTLK#4]
I've tested this addon in many instances and sometimes the damage displays on a different target, or it doesnt display at all. It works how it should sometimes, but most of the time it is either not showing damage at all or shows it on a different target. Link to example: [https://youtu.be/TkhY1_hInwQ](url)

**Comment by bkader** [comment]
Hello @TrippyDedd 
Try to download [this version](https://github.com/bkader/NameplateSCT_WoTLK/tree/48427957b8930d21e5d0f33af5fe6365600a30fe) and let me know if it works better than the one you have.

**Comment by TrippyDedd** [comment]
Hello @bkader I'll try this version out. I've tested it before with KUI Nameplates instead and had the same problem (on the version that I have). Will try with this version with and without ElvUI when I get the chance. Thank you for the quick response, cheers^^

**Comment by TrippyDedd** [comment]
@bkader  I see it's just a conflict with ElvUI, thank you :)

**Comment by bkader** [comment]
Hello again @TrippyDedd . I have completely rewritten the library and tested it on most addons, even on ElvUI, as long as _GUIDs_ are cached. Let me know if it works on your end with the new changes.
Cheers.
